<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Ярмарка</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta content="telephone=no" name="format-detection"/>
    <style type="text/css">
        .content a {
            color: #15c;
            border: none;
            text-decoration: none;
        }
    </style>
</head>
<body style="padding:0; margin:0; background:#FFF;">

<!-- Root -->
<table width="100%" cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td valign="top"
            style="padding: 35px 15px 40px 15px; background-color:#FFF; text-align:center; vertical-align:top;">
            <!-- Center -->
            <table cellspacing="0" cellpadding="0" border="0"
                   style="width: 100%; max-width: 615px; margin-left:auto; margin-right:auto;" class="content">
                <tr>
                    <td valign="top"
                        style="
                        text-align:left;
                        vertical-align:top; 
                        color:#000; 
                        font-size:13px; 
                        font-weight:normal; 
                        line-height:1.3;
                        padding: 0 26px 0 26px;
                        font-family:Arial, Helvetica, sans-serif;">

                        <!-- Content -->
                        <div style="margin-bottom:38px; background-color:#FFF;">
                            <?= $this->content; ?>

                            <!-- Signature -->
                            <div style="margin-bottom:38px; color:#000; font-size:13px; line-height: 1.6;">
                                <div>С уважением,<br/>ТД Ярмарка</div>
                            </div>
                            <!--/Signature -->

                        </div>
                        <!--/Content -->

                    </td>
                </tr>
            </table>
            <!--/Center -->

        </td>
    </tr>
</table>
<!--/Root -->

</body>
</html>
